### ISSUE TITLE
JNAInchi and OSGi

### ISSUE THREAD

**Issue by scootermorris** [dan2097/jna-inchi#25]
I have a cheminformatics app for Cytoscape called chemViz that uses CDK.  I was very excited to see that CDK was moving to use JNAInchi, but I have been unable to make it work with OSGi.   The problem is that the native code is not on a classpath since it's part of the OSGi bundle.  I can load native code using OSGi's implementation of System.loadLibrary(), which is bundle-aware, but System.load is not bundle aware, so JNA can't find the native modules.  Do you have anyone who has successfully used JNAInchi in an OSGi setting?

**Comment by Mailaender** [comment]
I can confirm that trying to consume this library via @eclipse-m2e will crash
```
Caused by: java.lang.NoClassDefFoundError: io/github/dan2097/jnainchi/InchiOptions$InchiOptionsBuilder
	at org.openscience.cdk.inchi.InChIGenerator.<clinit>(InChIGenerator.java:101)
	at org.openscience.cdk.inchi.InChIGeneratorFactory.getInChIGenerator(InChIGeneratorFactory.java:141)
```

**Comment by Mailaender** [comment]
Maybe not the most elegant solution, but I simply repackaged the library

https://github.com/OpenChrom/openchrom/commit/2e3f054a7f9b13cb5099254440d454cac7b2b403

The p2 update site is public.

**Comment by Mailaender** [comment]
It also solves these crashes https://github.com/dan2097/jna-inchi/blob/d70d3323e503f399dddc4dce055a200a484d78a7/jna-inchi-api/src/main/java/io/github/dan2097/jnainchi/JnaInchi.java#L828
